---
abstract: 'Graph database tables and relations'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GraphViz-DBI
provides:
  GraphViz::DBI:
    file: lib/GraphViz/DBI.pm
    version: 1.100860
requires:
  Carp: 0
  DBI: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Getopt::Long: 0
  GraphViz: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=GraphViz-DBI
  homepage: http://search.cpan.org/dist/GraphViz-DBI/
  repository: http://github.com/hanekomu/GraphViz-DBI
version: 1.100860
